insert into MOVIE (title, production,premiereDate,genre, director,description) values ( 'Lista Schindlera','USA', '13/11/1993','Dramat, Wojenny','Steven Spielberg', 'Historia przedsiębiorcy Oskara Schindlera, który podczas II wojny światowej uratował przed pobytem w obozach koncentracyjnych 1100 Żydów.' );
insert into MOVIE (title, production,premiereDate,genre, director,description) values ( 'Terminal', 'USA', '09/06/2004','Komedia romantyczna' , 'Steven Spielberg', 'Gdy Viktor Navorski, turysta z Europy Wschodniej, przylatuje do Nowego Jorku, w jego ojczyźnie ma miejsce zamach stanu. Amerykańskie władze nie uznają paszportu mężczyzny, więc miejscem przymusowego pobytu staje się dla niego hala terminalu.' );
insert into MOVIE (title, production,premiereDate,genre, director,description) values ( 'Wściekłe psy', 'USA', '21/01/1992','Thriller, Gangsterski' ,'Quentin Tarantino', 'Po nieudanym napadzie na sklep jubilerski kilku złodziei zdaje sobie sprawę, że jest wśród nich zdrajca, który powiedział policji o ich planie. ' );
insert into MOVIE (title, production,premiereDate,genre, director,description) values ( 'Jackie Brown', 'USA', '08/12/1997', 'Kryminał, Thriller', 'Quentin Tarantino',  'Stewardessa przyłapana na nielegalnym przewożeniu pieniędzy z Meksyku do Los Angeles rozpoczyna grę między agentami FBI a handlarzem broni, dla którego pracowała.' );
insert into MOVIE (title, production,premiereDate,genre, director,description) values ( 'Dzień świra', 'Polska', '07/06/2002','Dramat, Komedia, Psychologiczny' ,'Marek Koterski' ,  'Adaś Miauczyński, 49-letni rozwiedziony polonista, żyje w kręgu swoich natręctw, nie potrafiąc wyrwać się z nudy i rutyny dnia codziennego.' );
insert into MOVIE (title, production,premiereDate,genre, director,description) values ( 'Nic śmiesznego', 'Polska', '02/02/1996', 'Dramat, Komedia ', 'Marek Koterski ', 'Leżący w kostnicy reżyser wspomina swoje niezbyt zabawne życie.' );
insert into MOVIE (title, production,premiereDate,genre, director,description) values ( 'Incepcja', 'Wielka Brytania', '08/07/2010','Surrealistyczny, Thriller, Sci-Fi' , 'Christopher Nolan' , 'Czasy, gdy technologia pozwala na wchodzenie w świat snów. Złodziej Cobb ma za zadanie wszczepić myśl do śpiącego umysłu.' );
insert into MOVIE (title, production,premiereDate,genre, director,description) values ( 'Mroczny Rycerz', 'Wielka Brytania', '14/07/2008', 'Akcja, Sci-Fi' , 'Christopher Nolan' , 'Batman, z pomocą porucznika Gordona oraz prokuratora Harveya Denta, występuje przeciwko przerażającemu i nieobliczalnemu Jokerowi, który chce pogrążyć Gotham City w chaosie.' );
insert into MOVIE (title, production,premiereDate,genre, director,description) values ( 'Memento', 'USA', '05/09/2000', 'Kryminał, Thriller' , 'Christopher Nolan' , 'Leonard, szukający mordercy swojej żony, w wyniku wypadku traci pamięć krótkotrwałą. Nieustannie robi więc notatki i zdjęcia, a ważniejsze fakty tatuuje sobie na ciele.' );
insert into MOVIE (title, production,premiereDate,genre, director,description) values ( 'Nietykalni', 'Francja', '23/09/2011', 'Biograficzny, Dramat, Komedia' , 'Olivier Nakache' , 'Sparaliżowany milioner zatrudnia do opieki młodego chłopaka z przedmieścia, który właśnie wyszedł z więzienia.' );


